### PR TITLE
Fix Micro XRCE-DDS Agent tag

### PR DESCRIPTION
**Pull request by pablogs9**

### CODE REVIEW

**Comment by Ryanf55** [comment]
```
ryan@B650-970:~/Dev/ardu_ws$ colcon build --packages-up-to micro_ros_agent
Starting >>> micro_ros_agent
--- stderr: micro_ros_agent                             
Cloning into 'xrceagent'...
HEAD is now at 57d0862 Release v2.4.2
CMake Error at CMakeLists.txt:153 (find_package):
  By not providing "Findfastcdr.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fastcdr", but
  CMake did not find one.

  Could not find a package configuration file provided by "fastcdr"
  (requested version 1) with any of the following names:

    fastcdrConfig.cmake
    fastcdr-config.cmake

  Add the installation prefix of "fastcdr" to CMAKE_PREFIX_PATH or set
  "fastcdr_DIR" to a directory containing one of the above files.  If
  "fastcdr" provides a separate development package or SDK, be sure it has
  been installed.


gmake[5]: *** [CMakeFiles/uagent.dir/build.make:93: uagent-prefix/src/uagent-stamp/uagent-configure] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:83: CMakeFiles/uagent.dir/all] Error 2
gmake[3]: *** [Makefile:91: all] Error 2
gmake[2]: *** [CMakeFiles/xrceagent.dir/build.make:86: agent/src/xrceagent-stamp/xrceagent-build] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/xrceagent.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
---
Failed   <<< micro_ros_agent [2.65s, exited with code 2]

Summary: 0 packages finished [3.36s]
  1 package failed: micro_ros_agent
  1 package had stderr output: micro_ros_agent
  ```

**Comment by Ryanf55** [comment]
That's with a clean `build` directory.

**Comment by pablogs9** [comment]
Cannot replicate your error: https://asciinema.org/a/fJ5nyezqxUUJticc1tgQWaeWU

**Comment by pablogs9** [comment]
CI is passing, and in a clean ROS 2 Humble docker it works.

**Comment by Ryanf55** [comment]
Perhaps it's relying on an update in the base container that our CI doesn't have?
``` 
ryan@B650-970:~/Dev/ardu_ws$ apt list --upgradable | grep fast | grep humble

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

ros-humble-fastrtps/jammy 2.6.9-1jammy.20241120.162353 amd64 [upgradable from: 2.6.8-1jammy.20240728.201342]
ros-humble-rmw-fastrtps-cpp/jammy 6.2.7-1jammy.20241120.170829 amd64 [upgradable from: 6.2.7-1jammy.20240728.212513]
ros-humble-rmw-fastrtps-shared-cpp/jammy 6.2.7-1jammy.20241120.170038 amd64 [upgradable from: 6.2.7-1jammy.20240728.211440]
```

**Comment by pablogs9** [comment]
The issue is that I moved `ros2` branch from https://github.com/eProsima/Micro-XRCE-DDS-Agent/commit/57d086216d01ec43121845d385894a25987f8a2c to https://github.com/eProsima/Micro-XRCE-DDS-Agent/commit/73622810d984349b80bbac0ef55fc0b694d62222 in https://github.com/eProsima/Micro-XRCE-DDS-Agent. 

This bump included a Fast CDR bump usage to v2 APIs: https://github.com/eProsima/Micro-XRCE-DDS-Agent/commit/7d866fdfb85f89db845ff5e6f3e2fce5b68ac3a4

So nothing related with base container. 

It is just reverted and this PR fixes the potential movement of the remote `ros2` branch (already deprecated in `jazzy` and `rolling`).

**Comment by pablogs9** [comment]
Your Humble installation shall have:

```
root@7e60b325bd61:/# apt list  | grep fastcdr

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libfastcdr-dev/jammy 1.0.23-1 amd64
libfastcdr-doc/jammy 1.0.23-1 all
libfastcdr1/jammy 1.0.23-1 amd64
ros-humble-fastcdr-dbgsym/jammy 1.0.24-2jammy.20240728.192110 amd64
ros-humble-fastcdr/jammy,now 1.0.24-2jammy.20240728.192110 amd64 [installed,automatic]
ros-iron-fastcdr-dbgsym/jammy 1.0.27-3jammy.20240711.215604 amd64
ros-iron-fastcdr/jammy 1.0.27-3jammy.20240711.215604 amd64
ros-rolling-fastcdr-dbgsym/jammy 1.1.0-1jammy.20240124.150453 amd64
ros-rolling-fastcdr/jammy 1.1.0-1jammy.20240124.150453 amd64
```

**Comment by pablogs9** [comment]
Please confirm that your CI is ok with this change and I'll merge.

**Comment by Ryanf55** [comment]
CI re-run here: https://github.com/ArduPilot/ardupilot/actions/runs/12013146877

This CI is still using the `humble` branch.

**Comment by Ryanf55** [comment]
I ran CI on the `master` ardupilot branch here on my own repo. It should have less queue time.
https://github.com/Ryanf55/ardupilot/actions/runs/12015318375

**Comment by pablogs9** [comment]
Both are in green, merging.

**Pull request merged**
